cd build
cmake .. -DCMAKE_BUILD_TYPE=DEBUG \
-DLWS_WITH_LWSWS=1 \
# will enable
# -DLWS_WITH_LIBUV=1
-DLWS_WITH_STRUCT_JSON=1 \
-DLWS_WITH_MINIMAL_EXAMPLES=0 \
-DLWS_WITH_JOSE=0 \
-DCMAKE_INSTALL_PREFIX:PATH=/home/alex/git/libwebsockets/build/ \
-DLWS_WITH_FTS=1 \
-DLWS_WITHOUT_TESTAPPS=1 \
-DLWS_ROLE_WS=1 
#-DLWS_WITH_QBO=1
make
#make -n
