sonar.exclusions=**/*.pem,**/*.key,**/lws-ssh-test-keys,**/lws-ssh-test-keys.pub,**/localhost-100y.key

# Disable false positive security rules wholesale
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=c:S1313
sonar.issue.ignore.multicriteria.e1.resourceKey=**
sonar.issue.ignore.multicriteria.e2.ruleKey=secrets:S6706
sonar.issue.ignore.multicriteria.e2.resourceKey=**
sonar.issue.ignore.multicriteria.e3.ruleKey=secrets:*
sonar.issue.ignore.multicriteria.e3.resourceKey=**

