/*
 * libwebsockets - small server side websockets and web server implementation
 *
 * Copyright (C) 2010 - 2026 Andy Green <andy@warmcat.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * Native macOS DNS server discovery and change watching.
 *
 * /etc/resolv.conf on macOS is a compatibility file regenerated by configd
 * that only mirrors the primary service's resolvers; per-service and split
 * DNS resolver sets installed by VPNs and friends live only in the
 * SystemConfiguration dynamic store.  mDNSResponder consults the store, so
 * that's what we consult too.
 *
 * The watcher delivers dynamic store change callbacks on a private serial
 * dispatch queue (no runloop needed); they come back on a non-service
 * thread, and funnel into the generic, thread-safe
 * lws_adns_watch_trigger().
 */

#include "private-lib-core.h"
#include "private-lib-async-dns.h"

#include <TargetConditionals.h>

#if TARGET_OS_OSX

#include <SystemConfiguration/SCDynamicStore.h>
#include <dispatch/dispatch.h>

#define LWS_APPLE_DNS_MAX_SERVERS 16

/* dynamic store keys: the global (primary service) resolver set... */
static const CFStringRef lws_adns_key_global =
		CFSTR("State:/Network/Global/DNS");
/* ...and the effective resolver set of each active network service,
 * including any domain-scoped variants */
static const CFStringRef lws_adns_pat_services =
		CFSTR("State:/Network/Service/[^/]+/DNS.*");

typedef struct lws_adns_watch_apple {
	SCDynamicStoreRef	 store;
	dispatch_queue_t	 queue;
	struct lws_context	*cx;
} lws_adns_watch_apple_t;

/*
 * Collect the effective DNS server address strings from the dynamic store
 * into ads, global (primary service) resolvers first, then each active
 * service's set.  Returns the number collected.
 */

static int
lws_adns_store_list(SCDynamicStoreRef store, char ads[][48], int max)
{
	const void *kbuf[16], *vbuf[16];
	CFMutableArrayRef keys = NULL, pats = NULL;
	CFDictionaryRef resp = NULL;
	CFIndex count, n;
	int total = 0;

	keys = CFArrayCreateMutable(NULL, 1, &kCFTypeArrayCallBacks);
	pats = CFArrayCreateMutable(NULL, 1, &kCFTypeArrayCallBacks);
	if (!keys || !pats)
		goto bail;

	CFArrayAppendValue(keys, lws_adns_key_global);
	CFArrayAppendValue(pats, lws_adns_pat_services);

	resp = SCDynamicStoreCopyMultiple(store, (CFArrayRef)keys,
					  (CFArrayRef)pats);
	if (!resp)
		goto bail;

	/* the global (primary service) resolver set comes first */

	{
		CFDictionaryRef d = (CFDictionaryRef)CFDictionaryGetValue(
						resp, lws_adns_key_global);
		CFArrayRef a;
		CFIndex m;

		if (d && (a = (CFArrayRef)CFDictionaryGetValue(d,
					CFSTR("DNSServerAddresses"))))
			for (m = 0; m < CFArrayGetCount(a); m++) {
				if (total >= max)
					goto bail;
				if (!CFStringGetCString(
					(CFStringRef)CFArrayGetValueAtIndex(a, m),
					ads[total++], 48, kCFStringEncodingUTF8))
					total--;
			}
	}

	/* then every active network service's effective set */

	count = CFDictionaryGetCount(resp);
	if (count > (CFIndex)LWS_ARRAY_SIZE(kbuf))
		count = LWS_ARRAY_SIZE(kbuf);

	CFDictionaryGetKeysAndValues(resp, kbuf, vbuf);
	for (n = 0; n < count; n++) {
		CFDictionaryRef d = (CFDictionaryRef)vbuf[n];
		CFArrayRef a;
		CFIndex m;

		/* the global set was already added, above */

		if (CFEqual((CFStringRef)kbuf[n], lws_adns_key_global))
			continue;

		if (d && (a = (CFArrayRef)CFDictionaryGetValue(d,
					CFSTR("DNSServerAddresses"))))
			for (m = 0; m < CFArrayGetCount(a); m++) {
				if (total >= max)
					goto bail;
				if (!CFStringGetCString(
					(CFStringRef)CFArrayGetValueAtIndex(a, m),
					ads[total++], 48, kCFStringEncodingUTF8))
					total--;
			}
	}

bail:
	if (resp)
		CFRelease(resp);
	if (keys)
		CFRelease(keys);
	if (pats)
		CFRelease(pats);

	return total;
}

int
lws_plat_asyncdns_get_server(struct lws_context *context, int index,
			     lws_sockaddr46 *sa46)
{
	char ads[LWS_APPLE_DNS_MAX_SERVERS][48];
	SCDynamicStoreRef store;
	int total;

	store = SCDynamicStoreCreate(NULL, CFSTR("lws-adns"), NULL, NULL);
	if (store) {
		total = lws_adns_store_list(store, ads,
					    LWS_APPLE_DNS_MAX_SERVERS);
		CFRelease(store);

		if (total > index) {
			memset(sa46, 0, sizeof(*sa46));
			if (!lws_sa46_parse_numeric_address(ads[index], sa46))
				return 0;
		}

		if (total)
			/* we could read the store; past its list end */
			return -1;
	}

	/*
	 * The store yielded nothing at all, or we couldn't get a session for
	 * it... fall back to parsing the compat file, which mirrors the
	 * primary service's resolver set.  This is better than reporting no
	 * servers in restricted environments where the store isn't readable.
	 */

	return lws_asyncdns_parse_resolv_conf(context, index, sa46);
}

/*
 * Dynamic store change callback... runs on our private dispatch queue, ie,
 * a non-service thread.  Hand it to the generic acquisition + compare +
 * publish path, which is thread-safe.
 */

static void
lws_adns_store_cb(SCDynamicStoreRef store, CFArrayRef changedKeys, void *info)
{
	(void)store;
	(void)changedKeys;

	lws_adns_watch_trigger((struct lws_context *)info);
}

static void
lws_adns_drain_cb(void *unused)
{
	(void)unused;
}

int
lws_plat_asyncdns_watch_start(struct lws_context *cx)
{
	lws_adns_watch_apple_t *w = (lws_adns_watch_apple_t *)
							cx->async_dns.plat_watch;
	SCDynamicStoreContext sctx;
	CFMutableArrayRef keys = NULL, pats = NULL;

	if (w)
		return 0; /* already watching */

	w = lws_zalloc(sizeof(*w), __func__);
	if (!w)
		return 1;

	memset(&sctx, 0, sizeof(sctx));
	sctx.info = cx;

	w->cx = cx;
	w->store = SCDynamicStoreCreate(NULL, CFSTR("lws-adns-watch"),
					lws_adns_store_cb, &sctx);
	w->queue = dispatch_queue_create("com.warmcat.libwebsockets.adns",
					 DISPATCH_QUEUE_SERIAL);
	keys = CFArrayCreateMutable(NULL, 1, &kCFTypeArrayCallBacks);
	pats = CFArrayCreateMutable(NULL, 1, &kCFTypeArrayCallBacks);

	if (!w->store || !w->queue || !keys || !pats)
		goto bail;

	CFArrayAppendValue(keys, lws_adns_key_global);
	CFArrayAppendValue(pats, lws_adns_pat_services);

	if (!SCDynamicStoreSetNotificationKeys(w->store, (CFArrayRef)keys,
					       (CFArrayRef)pats))
		goto bail;

	/* deliver change callbacks on our queue instead of a runloop */
	if (!SCDynamicStoreSetDispatchQueue(w->store, w->queue))
		goto bail;

	cx->async_dns.plat_watch = w;

	CFRelease(keys);
	CFRelease(pats);

	return 0;

bail:
	if (keys)
		CFRelease(keys);
	if (pats)
		CFRelease(pats);
	if (w->store)
		CFRelease(w->store);
	if (w->queue)
		dispatch_release(w->queue);
	lws_free(w);

	return 1;
}

void
lws_plat_asyncdns_watch_stop(struct lws_context *cx)
{
	lws_adns_watch_apple_t *w = (lws_adns_watch_apple_t *)
							cx->async_dns.plat_watch;

	if (!w)
		return;

	cx->async_dns.plat_watch = NULL;

	/*
	 * The documented way to stop notifications... this also drops the
	 * store's reference on the queue.  Callbacks already dispatched may
	 * still be executing, so...
	 */
	if (w->store)
		SCDynamicStoreSetDispatchQueue(w->store, NULL);

	/* ...wait for any already-dispatched callback to have completed
	 * before the store and watcher state go away underneath it */

	dispatch_sync_f(w->queue, NULL, lws_adns_drain_cb);
	dispatch_release(w->queue);

	if (w->store)
		CFRelease(w->store);

	lws_free(w);
}

#else /* !TARGET_OS_OSX */

/*
 * On iOS-class Apple platforms the dynamic store apis aren't available; use
 * the shared resolv.conf parse (the file is maintained as a mirror of the
 * global resolver set) and rely on the generic poll for change detection.
 */

int
lws_plat_asyncdns_get_server(struct lws_context *context, int index,
			     lws_sockaddr46 *sa46)
{
	return lws_asyncdns_parse_resolv_conf(context, index, sa46);
}

int
lws_plat_asyncdns_watch_start(struct lws_context *cx)
{
	(void)cx;

	return 0;
}

void
lws_plat_asyncdns_watch_stop(struct lws_context *cx)
{
	(void)cx;
}

#endif
