project(lws-api-test-openssl-lifecycle C)
cmake_minimum_required(VERSION 3.10)
find_package(libwebsockets CONFIG REQUIRED)
list(APPEND CMAKE_MODULE_PATH ${LWS_CMAKE_DIR})
include(CheckCSourceCompiles)
include(LwsCheckRequirements)

set(SAMP lws-api-test-openssl-lifecycle)
set(SRCS main.c)

set(requirements 1)
require_lws_config(LWS_WITH_TLS 1 requirements)
require_lws_config(LWS_WITH_MBEDTLS 0 requirements)
require_lws_config(LWS_WITH_BORINGSSL 0 requirements)
require_lws_config(LWS_WITH_AWSLC 0 requirements)
require_lws_config(LWS_WITH_WOLFSSL 0 requirements)

if (requirements)
	add_executable(${SAMP} ${SRCS})
	add_test(NAME api-test-openssl-lifecycle COMMAND ${SAMP})
	set_tests_properties(api-test-openssl-lifecycle PROPERTIES TIMEOUT 30)

	if (websockets_shared)
		target_link_libraries(${SAMP} websockets_shared ${LIBWEBSOCKETS_DEP_LIBS})
		add_dependencies(${SAMP} websockets_shared)
	else()
		target_link_libraries(${SAMP} websockets ${LIBWEBSOCKETS_DEP_LIBS})
	endif()
endif()
